
name: 'dbt_trino'
version: '1.0.0'
config-version: 2

profile: 'dbt_trino'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]


models:
  dbtlearnnew:
    +materialized: view
    dim:
      +materialized: table
    src:
      +materialized: ephemeral