version: 2
sources:
  - name: airbnb
    schema: dbttesting
    tables:
      - name: listings
        identifier: src_listing
        
      - name: hosts
        identifier: scr_hosts

      - name: reviews
        identifier: src_reviews
        loaded_at_field: date
        freshness:
          warn_after: {count: 1, period: hour}
          error_after: {count: 24, period: hour}

